import { Metadata } from "next";
import CreativeNavBar from "@/components/landing/CreativeNavBar";
import Footer from "@/components/landing/Footer";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Secure AI Application Development | ZecurX",
    description: "We build AI-powered applications with security embedded from architecture to deployment. Secure MVPs, LLM integration, and AI threat modeling.",
    keywords: ["AI security", "LLM security", "secure AI development", "AI application security", "prompt injection", "AI threat modeling", "AI red teaming"],
    openGraph: {
        title: "Secure AI Application Development | ZecurX",
        description: "We build AI-powered applications with security embedded from architecture to deployment.",
        type: "website",
        url: "https://zecurx.com/services/secure-ai-development",
    },
    alternates: {
        canonical: "https://zecurx.com/services/secure-ai-development",
    },
};

const challenges = [
    {
        title: "Prompt Injection & Jailbreaks",
        desc: "LLMs are susceptible to adversarial inputs that can bypass safety filters and hijack model behavior. Attackers can use techniques like 'DAN' (Do Anything Now), role-playing attacks, or foreign language encoding to force the model to generate harmful content, execute unauthorized commands, or reveal its system instructions. Traditional WAFs cannot detect these semantic attacks."
    },
    {
        title: "Data Leakage & Privacy",
        desc: "Generative AI models can inadvertently memorize and regurgitate sensitive information found in their training data or context window. This creates a significant risk of PII exposure, leakage of trade secrets, or accidental disclosure of proprietary codebases. Once data is generated by the model, it's difficult to 'unlearn' or redact it reliably."
    },
    {
        title: "Supply Chain Vulnerabilities",
        desc: "Modern AI stacks rely heavily on open-source models (Hugging Face), vector databases, and orchestration frameworks (LangChain). Malicious actors can poison these dependencies, inject backdoors into model weights (Pickle files), or exploit vulnerabilities in third-party plugins to compromise your entire AI infrastructure."
    },
    {
        title: "Non-Deterministic Output & Hallucinations",
        desc: "Unlike traditional deterministic software, AI behavior is probabilistic. Models can confidently generate false information (hallucinations) or behave inconsistently under load. Ensuring consistent, safe, and reliable outputs requires a new paradigm of testing that includes evaluating factual accuracy, toxicity, and bias at scale."
    }
];

const capabilities = [
    {
        title: "AI Red Teaming",
        desc: "We conduct adversarial simulation to stress-test your models against real-world attacks. Our team attempts advanced prompt injections, jailbreaks, and extraction attacks to find weaknesses before you deploy. We evaluate your model's resilience against manipulation and its adherence to safety guidelines."
    },
    {
        title: "Secure RAG Architecture",
        desc: "We design and review Retrieval-Augmented Generation systems to prevent unauthorized data access. We ensure your vector databases and retrieval logic implement strict access controls (RBAC) so users only retrieve documents they are authorized to see, preventing 'context leakage' between tenants or user roles."
    },
    {
        title: "LLM Guardrails Implementation",
        desc: "We develop robust input/output filtering layers to sanitize interactions. Using frameworks like NeMo Guardrails or custom classifiers, we block malicious prompts before they reach your model and filter out toxic or unsafe responses before they reach your users, ensuring brand safety."
    },
    {
        title: "Agentic AI Security",
        desc: "Autonomous agents with tool access pose high risks. We secure your agent execution environments by implementing strict permission boundaries, human-in-the-loop verification for critical actions, and sandboxing to prevent an agent from being tricked into performing destructive actions via indirect prompt injection."
    },
    {
        title: "Model Supply Chain Review",
        desc: "We perform deep vulnerability scanning for your AI artifacts. This includes scanning model files for malicious code, analyzing dependencies for known vulnerabilities, and verifying the integrity of your training datasets to prevent poisoning attacks."
    },
    {
        title: "Compliance & Governance",
        desc: "We help you align with emerging global AI standards. We prepare your systems for the EU AI Act, NIST AI Risk Management Framework (AI RMF), and ISO 42001, ensuring you meet regulatory requirements for transparency, risk management, and data governance."
    }
];

const methodology = [
    {
        step: "01",
        title: "Threat Modeling",
        desc: "We analyze your specific AI use case to identify unique attack surfaces, from data ingestion to model output."
    },
    {
        step: "02",
        title: "Architecture Review",
        desc: "We assess your RAG pipelines, vector stores, and API integrations for design flaws and access control issues."
    },
    {
        step: "03",
        title: "Adversarial Testing",
        desc: "Our red team executes targeted campaigns using automated fuzzing and manual expertise to bypass your guardrails."
    },
    {
        step: "04",
        title: "Remediation & Hardening",
        desc: "We provide code-level fixes, prompt engineering adjustments, and architectural changes to close security gaps."
    }
];

export default function SecureAIDevelopmentPage() {
    return (
        <main className="bg-background min-h-screen text-foreground selection:bg-primary/30 relative overflow-hidden">
            <CreativeNavBar />

            <section className="relative pt-32 pb-20 px-6">
                <div className="absolute inset-0 z-0 h-full w-full bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:48px_48px] pointer-events-none" />
                <div className="absolute top-20 left-0 w-[400px] h-[400px] bg-foreground/3 blur-[120px] rounded-full pointer-events-none" />

                <div className="max-w-7xl mx-auto relative z-10">
                    <div className="mb-8">
                        <span className="text-xs font-semibold text-muted-foreground uppercase tracking-[0.2em]">
                            Build & Secure
                        </span>
                    </div>

                    <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight text-foreground mb-6 leading-[1.1]">
                        Secure AI Application Development
                    </h1>

                    <p className="text-xl text-muted-foreground leading-relaxed max-w-2xl mb-12">
                        Ship AI with confidence. We help you build, test, and deploy secure LLM applications, protecting against prompt injection, data leakage, and model theft.
                    </p>

                    <div className="flex flex-wrap gap-4">
                        <Link
                            href="/contact"
                            className="px-8 py-4 bg-foreground text-background font-semibold rounded-full hover:opacity-90 transition-opacity"
                        >
                            Build With Us
                        </Link>
                        <Link
                            href="/how-we-work"
                            className="px-8 py-4 border border-border text-foreground font-medium rounded-full hover:bg-muted/50 transition-colors"
                        >
                            How We Work
                        </Link>
                    </div>
                </div>
            </section>

            <div className="w-full h-px bg-border/40 max-w-7xl mx-auto px-6" />

            <section className="py-24 px-6 border-t border-white/5">
                <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-12 lg:gap-24">
                    <div className="lg:col-span-1">
                        <div className="sticky top-32">
                            <h2 className="text-3xl font-bold text-foreground mb-6 leading-tight">
                                Why AI Security <br />
                                <span className="text-muted-foreground">Is Different</span>
                            </h2>
                            <p className="text-muted-foreground text-lg leading-relaxed mb-8">
                                Traditional application security isn&apos;t enough. Generative AI introduces probabilistic risks that standard firewalls and scanners miss.
                            </p>
                            <div className="hidden lg:block w-12 h-1 bg-primary mb-8" />
                        </div>
                    </div>

                    <div className="lg:col-span-2 flex flex-col">
                        {challenges.map((item, i) => (
                            <div key={i} className="group py-8 border-t border-white/10 first:border-0 first:pt-0">
                                <h3 className="text-xl font-bold text-foreground mb-3 group-hover:text-primary transition-colors flex items-center gap-3">
                                    <span className="text-xs font-mono text-primary/50 border border-primary/20 px-2 py-1 rounded">0{i + 1}</span>
                                    {item.title}
                                </h3>
                                <p className="text-muted-foreground leading-relaxed text-lg pl-12">
                                    {item.desc}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            <section className="py-24 px-6 bg-muted/5 border-t border-white/5">
                <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-12 lg:gap-24">
                    <div className="lg:col-span-1">
                        <div className="sticky top-32">
                            <h2 className="text-3xl font-bold text-foreground mb-6 leading-tight">
                                Our AI Security <br />
                                <span className="text-muted-foreground">Capabilities</span>
                            </h2>
                            <p className="text-muted-foreground text-lg leading-relaxed mb-8">
                                From red teaming foundation models to securing RAG pipelines, we cover the entire AI lifecycle.
                            </p>
                            <div className="hidden lg:block w-12 h-1 bg-primary mb-8" />
                        </div>
                    </div>

                    <div className="lg:col-span-2 grid grid-cols-1 gap-12">
                        {capabilities.map((item, i) => (
                            <div key={i} className="group relative pl-8 border-l border-white/10 hover:border-primary/50 transition-colors py-2">
                                <h3 className="text-xl font-bold text-foreground mb-3 group-hover:text-primary transition-colors">
                                    {item.title}
                                </h3>
                                <p className="text-muted-foreground leading-relaxed text-lg">
                                    {item.desc}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            <section className="py-24 px-6 border-t border-white/5">
                <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-12 lg:gap-24">
                    <div className="lg:col-span-1">
                        <div className="sticky top-32">
                            <h2 className="text-3xl font-bold text-foreground mb-6 leading-tight">
                                How We Secure <br />
                                <span className="text-muted-foreground">Your AI</span>
                            </h2>
                            <p className="text-muted-foreground text-lg leading-relaxed mb-8">
                                A structured, risk-based approach to AI adoption. We move from threat modeling to continuous monitoring.
                            </p>
                            <div className="hidden lg:block w-12 h-1 bg-primary mb-8" />
                        </div>
                    </div>

                    <div className="lg:col-span-2 flex flex-col">
                        {methodology.map((item, i) => (
                            <div key={i} className="group py-8 border-t border-white/10 first:border-0 first:pt-0">
                                <span className="text-xs font-mono text-primary/50 mb-3 block">PHASE {item.step}</span>
                                <h3 className="text-xl font-bold text-foreground mb-3 group-hover:text-primary transition-colors">
                                    {item.title}
                                </h3>
                                <p className="text-muted-foreground leading-relaxed text-lg">
                                    {item.desc}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            <section className="py-20 px-6">
                <div className="max-w-7xl mx-auto">
                    <div className="p-8 md:p-12 rounded-3xl border border-border/40 bg-card/20">
                        <h2 className="text-2xl md:text-3xl font-semibold text-foreground mb-4">
                            Building with LLMs?
                        </h2>
                        <p className="text-muted-foreground mb-8 max-w-xl">
                            Don&apos;t let security block your innovation. Let us help you ship secure AI applications faster.
                        </p>
                        <Link
                            href="/contact"
                            className="inline-flex px-8 py-4 bg-foreground text-background font-semibold rounded-full hover:opacity-90 transition-opacity"
                        >
                            Start Your AI Assessment
                        </Link>
                    </div>
                </div>
            </section>

            <Footer />
        </main>
    );
}
